default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "" %>
  pool: 5

development:
  <<: *default
  database: calorie_app_api_development

test:
  <<: *default
  database: calorie_app_api_test

production:
  <<: *default
  database: calorie_app_api_production
  username: <%= ENV["PG_PROD_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PROD_PASSWORD"] || "" %>
  host: <%= ENV["PG_PROD_HOST"] || "localhost" %>
